### ISSUE TITLE
Update job

### ISSUE THREAD

**Issue by thetillhoff** [mohoff/mohoff.de#1]
Please update your job:
https://github.com/mohoff/mohoff.de/blob/ccd61e44785a945193cbd3e2bdaf63a0a64978e5/mohoff.de/index.html#L27

**Comment by thetillhoff** [comment]
Will close this stale issue.

**Comment by mohoff** [comment]
@tillhoff erledigt in https://github.com/mohoff/mohoff.de/commit/5cccb99c29327790eda5fe3b99a169ff8ec54ead. Danke brudi
